export const GET_USERS = 'GET_USERS';
export const LOAD_USER = 'LOAD_USER';

export const GET_POLLS = 'GET_POLLS';
export const GET_CATEGORY_POLLS = 'GET_CATEGORY_POLLS';
export const SET_POLL_QUESTION = 'SET_POLL_QUESTION';
export const ADD_POLL_QUESTION = 'ADD_POLL_QUESTION';
export const SAVE_POLL_ANSWER = 'SAVE_POLL_ANSWER';
export const REMOVE_POLL_ANSWER = 'REMOVE_POLL_ANSWER';

export const LOAD_LEADERBOARD = 'LOAD_LEADERBOARD';